name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          toolchain: stable
          profile: minimal
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: build-${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}
      - name: Run tests
        run: cargo test --all
